version: '3.8'

services:
  ex-log-app:
    build: .
    container_name: ex-log-app
    ports:
      - "8080:8080"
    environment:
      # .env 파일에 적힌 값을 컨테이너 내부로 토스
      - DB_HOST=ex-log-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - ex-log-db
    networks:
      - ex-log-network

  ex-log-db:
    image: mysql:8.0
    container_name: ex-log-db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - ex-log-network

networks:
  ex-log-network:
    driver: bridge